### ISSUE TITLE
Is there a way to get/ edit Estimates?

### ISSUE THREAD

**Issue by grantkemp** [MattCheetham/HarvestKit-Swift#94]
Hi -great job on the kit.
 Is there a way to manage estimates via this? I want to generate/ edit.

**Comment by MattCheetham** [comment]
Hey!

It looks like at this time that the Harvest API [doesn't support estimates](http://help.getharvest.com/api/invoices-api/invoices/estimates-not-supported/) which sucks. If they ever add support I'll get it in here as soon as I can for you.
